<?php
/**
 *
 * author: jinyanxin
 * Date: 2020/8/31
 * Time: 11:10
 * PHP version 7
 */

namespace backend\models;


use yii\base\Model;

class BaseForm extends Model
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }


    /**
     * @duty 将金额转为分为单位
     * @param float $amount
     * @return integer
     */
    public static function amountToCent($amount){
        return  intval($amount*100);
    }

    /**
     * @duty 将金额转为元为单位,并保留两位小数
     * @param integer $amount
     * @return float
     */
    public static function amountToYuan($amount){
        return  sprintf("%.2f",$amount/100);
    }

}